// Generates assets/tokens.css from a per-client config in clients/<name>/config.json.
// Client is selected via the CLIENT env var (defaults to "default").
import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import path from 'node:path'

const rootDir = path.dirname(path.dirname(fileURLToPath(import.meta.url)))
const client = process.env.CLIENT || 'default'
const configPath = path.join(rootDir, 'clients', client, 'config.json')
const outputPath = path.join(rootDir, 'assets', 'tokens.css')

const config = JSON.parse(readFileSync(configPath, 'utf8'))

const css = `/*
  Design tokens — generated from clients/${client}/config.json by scripts/generate-tokens.mjs.
  Do not edit this file directly; edit the client config and rerun \`npm run tokens\`.
*/
:root {
  --color-primary: ${config.colors.primary};
  --color-secondary: ${config.colors.secondary};
  --color-background: ${config.colors.background};
  --color-foreground: ${config.colors.foreground};
  --font-heading: ${config.fonts.heading};
  --font-body: ${config.fonts.body};
  --border-radius: ${config.borderRadius};
  --spacing-base: ${config.spacingBase};
}
`

writeFileSync(outputPath, css)
console.log(`Generated ${path.relative(rootDir, outputPath)} from ${path.relative(rootDir, configPath)}`)
